# Create a service with specification and check for same post creation
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service 
  namespace: default
spec:
  ports:
  - nodePort: 30080
    port: 8080
    targetPort: 8080 
  selector:
    name: simple-webapp
  type: NodePort

controlplane ~ ➜  

controlplane ~ ➜  

controlplane ~ ➜  kubectl apply -f service-definition-1.yaml 
service/webapp-service created

controlplane ~ ➜  kubectl get svc
NAME             TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
kubernetes       ClusterIP   10.43.0.1      <none>        443/TCP          11m
webapp-service   NodePort    10.43.67.103   <none>        8080:30080/TCP   10s

controlplane ~ ➜  

controlplane ~ ➜  kubectl describe service webapp-service
Name:                     webapp-service
Namespace:                default
Labels:                   <none>
Annotations:              <none>
Selector:                 name=simple-webapp
Type:                     NodePort
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.43.67.103
IPs:                      10.43.67.103
Port:                     <unset>  8080/TCP
TargetPort:               8080/TCP
NodePort:                 <unset>  30080/TCP
Endpoints:                10.22.0.12:8080,10.22.0.11:8080,10.22.0.9:8080 + 1 more...
Session Affinity:         None
External Traffic Policy:  Cluster
Internal Traffic Policy:  Cluster
Events:                   <none>

controlplane ~ ➜  
