=======================================
Horizontal Pod AutoScaler.
=======================================

controlplane ~ ➜  ls -ltr
total 8
-rw-r--r-- 1 root root 340 Sep  3 05:54 deployment.yml
-rw-r--r-- 1 root root 949 Sep  6 07:59 skooner-sa-token.txt

controlplane ~ ➜  

controlplane ~ ➜  cat deployment.yml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 7
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
controlplane ~ ➜  

controlplane ~ ➜  k apply -f deployment.yml 
deployment.apps/nginx-deployment created

controlplane ~ ➜  

controlplane ~ ➜  k get deployments.apps nginx-deployment 
NAME               READY   UP-TO-DATE   AVAILABLE   AGE
nginx-deployment   7/7     7            7           15s

controlplane ~ ➜  

controlplane ~ ➜  

controlplane ~ ➜  k get all
NAME                                    READY   STATUS    RESTARTS   AGE
pod/nginx-deployment-77bc6bd484-7krtv   1/1     Running   0          19s
pod/nginx-deployment-77bc6bd484-cljb8   1/1     Running   0          19s
pod/nginx-deployment-77bc6bd484-f4kcz   1/1     Running   0          19s
pod/nginx-deployment-77bc6bd484-fm4ct   1/1     Running   0          19s
pod/nginx-deployment-77bc6bd484-lxkz9   1/1     Running   0          19s
pod/nginx-deployment-77bc6bd484-q86hb   1/1     Running   0          19s
pod/nginx-deployment-77bc6bd484-qntwp   1/1     Running   0          19s

NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   172.20.0.1   <none>        443/TCP   54m

NAME                               READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/nginx-deployment   7/7     7            7           19s

NAME                                          DESIRED   CURRENT   READY   AGE
replicaset.apps/nginx-deployment-77bc6bd484   7         7         7       19s

controlplane ~ ➜  

controlplane ~ ➜  

controlplane ~ ➜  cat skooner-sa-token.txt 
eyJhbGciOiJSUzI1NiIsImtpZCI6IjlYbnBzU1FFcS1PY0Z1YUVYS2RxUEFTaXJlZHhlNEFjcndYVkZkY1Y0bWcifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzg4Njg1MTY4LCJpYXQiOjE3ODg2ODE1NjgsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiMzA1NmRhNmEtNWYxNC00NDM5LWJhZTUtMmFkZTEwZDg5Njk2Iiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJza29vbmVyLXNhIiwidWlkIjoiZDU0ODVkMDMtNDg1ZC00NzJhLTlhZGUtYWVhNGY4YTk4ZWYwIn19LCJuYmYiOjE3ODg2ODE1NjgsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTpza29vbmVyLXNhIn0.Re95pkkJpr2q33KS9pNkKj3puh8eLK8o30rEm1p_j47ckUl4nV4k8l-0oQc6ZuAeFfmTOg0eRr6zOxhv9vvY4KaymPw3hgHCbd_wSIdP00FWXgOaFsmo0-fDJdU0XHOJr6oMfPkcxn1YdtJz_vWJcauC8yFIhAS_KuZFr_g-9kVRUQDBFlNJ3YFhfE2NO0BCzJ1Wp7wu4wwxyj8N_4qv_HQst_AH1gmX7Zd1KLUAAzQ33x7dqvwvC0DdBvdShXOHapUhAO51dzv21psQi2jdOKbhqFxLqgaP6_tGKD7ZjSWe6e2tImx7IG9Ehdkc9lmijtSz42wBhdrf0eig9fpjAg
controlplane ~ ➜  

controlplane ~ ➜  

controlplane ~ ➜  

controlplane ~ ➜  ls -ltr
total 12
-rw-r--r-- 1 root root 340 Sep  3 05:54 deployment.yml
-rw-r--r-- 1 root root 455 Sep  3 05:54 autoscale.yml
-rw-r--r-- 1 root root 949 Sep  6 07:59 skooner-sa-token.txt

controlplane ~ ➜  cat autoscale.yml 
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: null
  name: nginx-deployment
spec:
  maxReplicas: 3
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment
status:
  currentMetrics: null
  desiredReplicas: 0
  currentReplicas: 0
controlplane ~ ➜  

controlplane ~ ➜  

controlplane ~ ➜  k apply -f autoscale.yml 
horizontalpodautoscaler.autoscaling/nginx-deployment created

controlplane ~ ➜  

controlplane ~ ➜  

controlplane ~ ➜  k get hpa
NAME               REFERENCE                     TARGETS              MINPODS   MAXPODS   REPLICAS   AGE
nginx-deployment   Deployment/nginx-deployment   cpu: <unknown>/80%   1         3         0          5s

controlplane ~ ➜  

controlplane ~ ➜  k get all
NAME                                    READY   STATUS    RESTARTS   AGE
pod/nginx-deployment-77bc6bd484-7krtv   1/1     Running   0          3m37s
pod/nginx-deployment-77bc6bd484-lxkz9   1/1     Running   0          3m37s
pod/nginx-deployment-77bc6bd484-q86hb   1/1     Running   0          3m37s

NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   172.20.0.1   <none>        443/TCP   58m

NAME                               READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/nginx-deployment   3/3     3            3           3m37s

NAME                                          DESIRED   CURRENT   READY   AGE
replicaset.apps/nginx-deployment-77bc6bd484   3         3         3       3m37s

NAME                                                   REFERENCE                     TARGETS              MINPODS   MAXPODS   REPLICAS   AGE
horizontalpodautoscaler.autoscaling/nginx-deployment   Deployment/nginx-deployment   cpu: <unknown>/80%   1         3         3          60s

controlplane ~ ➜  

controlplane ~ ➜  cat deployment.yml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 7
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
         requests:
           cpu: 100m
         limits:
           cpu: 200m

controlplane ~ ➜  vi deployment_before.yml 

controlplane ~ ➜  

controlplane ~ ➜  

controlplane ~ ➜  diff deployment.yml deployment_before.yml 
22,26d21
<         resources:
<          requests:
<            cpu: 100m
<          limits:
<            cpu: 200m

controlplane ~ ✖ 

controlplane ~ ✖ 

controlplane ~ ✖ k apply -f deployment.yml 
deployment.apps/nginx-deployment configured

controlplane ~ ➜  k get hpa -w
NAME               REFERENCE                     TARGETS              MINPODS   MAXPODS   REPLICAS   AGE
nginx-deployment   Deployment/nginx-deployment   cpu: <unknown>/80%   1         3         3          3m13s
nginx-deployment   Deployment/nginx-deployment   cpu: <unknown>/80%   1         3         7          3m15s
nginx-deployment   Deployment/nginx-deployment   cpu: 0%/80%          1         3         3          3m30s
nginx-deployment   Deployment/nginx-deployment   cpu: 0%/80%          1         3         3          5m15s
nginx-deployment   Deployment/nginx-deployment   cpu: 0%/80%          1         3         1          5m30s
^C
controlplane ~ ✖ 

controlplane ~ ✖ 

controlplane ~ ✖ k event hpa nginx-deployment | grep -i "ScalingReplicaSet "
error: unknown command "event" for "kubectl"

Did you mean this?
        events

controlplane ~ ✖ k events hpa nginx-deployment | grep -i "ScalingReplicaSet "
9m19s                   Normal    ScalingReplicaSet              Deployment/nginx-deployment                Scaled up replica set nginx-deployment-77bc6bd484 from 0 to 7
6m27s                   Normal    ScalingReplicaSet              Deployment/nginx-deployment                Scaled down replica set nginx-deployment-77bc6bd484 from 7 to 3
3m37s                   Normal    ScalingReplicaSet              Deployment/nginx-deployment                Scaled up replica set nginx-deployment-77bc6bd484 from 3 to 7
3m37s                   Normal    ScalingReplicaSet              Deployment/nginx-deployment                Scaled up replica set nginx-deployment-766d5b75cd from 0 to 2
3m37s                   Normal    ScalingReplicaSet              Deployment/nginx-deployment                Scaled down replica set nginx-deployment-77bc6bd484 from 7 to 6
3m37s                   Normal    ScalingReplicaSet              Deployment/nginx-deployment                Scaled up replica set nginx-deployment-766d5b75cd from 2 to 3
3m34s                   Normal    ScalingReplicaSet              Deployment/nginx-deployment                Scaled up replica set nginx-deployment-766d5b75cd from 3 to 4
3m34s                   Normal    ScalingReplicaSet              Deployment/nginx-deployment                Scaled down replica set nginx-deployment-77bc6bd484 from 6 to 5
3m34s                   Normal    ScalingReplicaSet              Deployment/nginx-deployment                Scaled down replica set nginx-deployment-77bc6bd484 from 5 to 4
87s (x9 over 3m34s)     Normal    ScalingReplicaSet              Deployment/nginx-deployment                (combined from similar events): Scaled down replica set nginx-deployment-766d5b75cd from 3 to 1

controlplane ~ ➜  

controlplane ~ ➜  

controlplane ~ ➜  k events hpa nginx-deployment | grep -i "FailedGetResourceMetric" 
4m37s (x5 over 6m37s)   Warning   FailedGetResourceMetric        HorizontalPodAutoscaler/nginx-deployment   failed to get cpu utilization: missing request for cpu in container nginx of Pod nginx-deployment-77bc6bd484-lxkz9
4m22s (x4 over 6m22s)   Warning   FailedGetResourceMetric        HorizontalPodAutoscaler/nginx-deployment   failed to get cpu utilization: missing request for cpu in container nginx of Pod nginx-deployment-77bc6bd484-7krtv
4m7s (x2 over 6m7s)     Warning   FailedGetResourceMetric        HorizontalPodAutoscaler/nginx-deployment   failed to get cpu utilization: missing request for cpu in container nginx of Pod nginx-deployment-77bc6bd484-q86hb

controlplane ~ ➜  

controlplane ~ ➜  
