kubeConfig - user certificate and key verify and update
------------------------------------------------------

controlplane ~ ➜  cd /root/.kube/

controlplane ~/.kube ➜  ls -la
total 24
drwxr-xr-x 3 root root 4096 Sep 10 14:08 .
drwx------ 1 root root 4096 Sep 10 14:16 ..
drwxr-x--- 4 root root 4096 Sep 10 14:08 cache
-rw------- 1 root root 5640 Sep 10 14:08 config

controlplane ~/.kube ➜  cat config 
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJZmlOK01BLy9YN1l3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBNU1UQXhOREF5TlRKYUZ3MHpOakE1TURjeE5EQTNOVEphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURqNkdKdXd0NXhlQ2pIRTREV2VzK21rL1Z6QlRMYUxUeEpJclZnVXArVXVkVHdUdmZFaXdsQ3hhZ1UKSjlCcnZhdkY2RThxalVZOHpDTHBZdk9hVUFpY2N2M0t2c3JHZzlwaUdzN2JpMXBuVVRtU3ZSelp6UzZNSEZiNQp6UUJmcWJoVUtTUXJaZG1RVEp6Wmh2QitTSkpxd3BubC96SCthM0oyVjVaWVNibjFmNkNkY2p3Nm04L0xqNEFvCnRWMld1R3AxWkttODg1eXU0S1B6VzJmZGg0UFl6QmQ2T21hREpWU3VyOVl6ejU0RGxmNzVENDJFSG5XYTUyaEgKaHZjaUhic1FnM1ZraE9RemdjS1hUSVE2YUxHcmRxNTg1ejRzU0RRbnYzN2hkU0tFSDBXeGI1TG0vMysyT0xyQgp6dXpVRnM4OTVEc0k4L1BlR3Q4YWNBK09KZlE3QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRSDMzVC9KSERHRW5aSkVLcm5LYzNJdVh1Vkl6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQk1mbk4vMTNITAppQTBVVXNEcmY0ZW5MUHhjSVlHM0xOaTBQczZWMlc5OUdWbmZML00rdTZBWXUrTFVpR3ZmVXBwMERiN0xJbEZRCkpyVEJiaXZPd3FmbnovT3lJM1QwTlNhVnNVVXdTQ3FpRXc4YlIxTk5aRFFiMGdBWjNpQnh5VHlsRXVETXZaSDIKR3p1UE9ndVk4NUZ0MnZFcTFlOXlza1VRQjlLa1F1MjEzVWhXazQzTm9YWEFrTXJMQ3lVZkRzNDU3VFA1U2t3NQphWUhkaEZmdWRJK3Y3RTkvc2ZmRlhjQUluZUxxSmM2c3VNV2JxWW0rMFVDTjAxQkxPOHFLSksxeVJ4NURCYTNaCkl5emswZ0drUy9pWnpUZ1ppbnZoZno5YXdPYktHODYxd2ZISGZHV2IrQTV1Zk8zQzFIZnBoZkkrd2lYQ2c2aGEKNGxHSGM0ZkxWa1d4Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://controlplane:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
users:
- name: kubernetes-admin
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLVENDQWhHZ0F3SUJBZ0lJVGY3T012bGxYSzh3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBNU1UQXhOREF5TlRKYUZ3MHlOekE1TVRBeE5EQTNOVEphTUR3eApIekFkQmdOVkJBb1RGbXQxWW1WaFpHMDZZMngxYzNSbGNpMWhaRzFwYm5NeEdUQVhCZ05WQkFNVEVHdDFZbVZ5CmJtVjBaWE10WVdSdGFXNHdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEemdaMTcKbDdQUERHdGc3UkdRQ0NKZDhCbm85bGRGUnRTbFg5SWlLb0RvaEg1Wm1LaDJXdnl5WEhmK09jRElPNFoycWgyZAozWFBsL1F5cnNtdHhtRlhRZm0zQ0g0WVlCeFNIamhIRm5iaXBWRHdGeXl3SDZFZzAyaHkrN1ZrdEhkVDA0aE9MCkxWSmJqV1dTZGo1RUpUYmNsWm1RYVhBN3JjdUxReFBFT1FYb2NPZUNFTytNYjJrV2RzcmFQU1M4aDkxMjNEREkKaDlmTU82NWhJVTBQU2RJWFhGY3ZVU3VJd291NmJsbkhyRWY5T3VHTnhLSFZQYm1qa0FlZXhNTzRnZDFvTHpXeAo2RW42R2JzbDhKSkNlSjBmaTJwSXJsb0RTaVN6SktBVCtueFdWRjU0Y3RmYUU2QXJSNklzMEFnVS9KZS9ITWt0Ck5EdGIxajRWRVRST0M2cVpBZ01CQUFHalZqQlVNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUsKQmdnckJnRUZCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjhHQTFVZEl3UVlNQmFBRkFmZmRQOGtjTVlTZGtrUQpxdWNwemNpNWU1VWpNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUNVS1pjWUZaVFlGbks3azg4VzZnRG9LZTBLCnBidlFGRzlobi9oSEdsa0VqK2l2bHVkTjh6L0NueWVURU5PdE10emtvK3ptclhtZEVaKzR5UmJJdDdqLzIzc0UKd0ZlR1FHRW4wZjlYR3BwSEYrUDN1UGNYZCt1c0M4TVNWVGcyZjZ4R0FpTGF5c0lFbnc3akx1VHFhRndIbUhoOQpDUjlpSWJlQ05Pb0ticHBGZ3RRWlIrTW9tazV6N3J4TUg1ZEV4b01PS0owYWJLS21NTnkzejF1ZVJvYTFqNUZaCmxXbEdUc0t4dkZDVURpZ3ZheWgrZFVib29oa2FSeEd1Q0paZFpzTXRSSnZsS202dWtZcHJUVDJlUUZzQ2MyUVoKdXVBZmxuQzdkRXZuN28vNFJRcFRPRVZ3L0kyN084NExIZjlqRFVNM25UWEtJdlZibytVWkwwZjJmenlUCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBODRHZGU1ZXp6d3hyWU8wUmtBZ2lYZkFaNlBaWFJVYlVwVi9TSWlxQTZJUitXWmlvCmRscjhzbHgzL2puQXlEdUdkcW9kbmQxejVmME1xN0pyY1poVjBINXR3aCtHR0FjVWg0NFJ4WjI0cVZROEJjc3MKQitoSU5Ob2N2dTFaTFIzVTlPSVRpeTFTVzQxbGtuWStSQ1UyM0pXWmtHbHdPNjNMaTBNVHhEa0Y2SERuZ2hEdgpqRzlwRm5iSzJqMGt2SWZkZHR3d3lJZlh6RHV1WVNGTkQwblNGMXhYTDFFcmlNS0x1bTVaeDZ4SC9UcmhqY1NoCjFUMjVvNUFIbnNURHVJSGRhQzgxc2VoSitobTdKZkNTUW5pZEg0dHFTSzVhQTBva3N5U2dFL3A4VmxSZWVITFgKMmhPZ0swZWlMTkFJRlB5WHZ4ekpMVFE3VzlZK0ZSRTBUZ3VxbVFJREFRQUJBb0lCQUNlYXBpVnExL2pOMlUwTApZYmJlUzlDaGMyVmJZM2hGKytIbHdzU0J5ek9HRVJLN2JITExlNXY2eEIxYUFVdlB1cC9rTFNyMjBKblFYVll6Cmo1d0xIYkhxVGltcmZPQzlqZzQ2QWhQMUFncXdRNDdocTRpaHM5Uzh3TDRnMWtjck9lNldNbjJKWW9LM2JaU3oKbkk3eXlvaDM0R0VIZFJTUHdMSW10N2xMV1BXanpod2lTbmE2aUY4Smc5dTROU1E3U215bmwrNWl4MzcyUWcrOAptSlgrZlZiT2FLNThITmdxR0p2Y0RIRjFxR1I2V0dobVNDdkZwZzdVb0ZYSHo0Z0c0Q210bkZCU2JxWDJmQU5qCmI3OVhwYkpBSEswSmdFbUx3c1NONkpaYlhLanNxZ1NSTEc0aWdqakhsd29Zd1BObDBGVzV2bS9wSG5YSThxcW0KRi8rNTdCMENnWUVBK2JjbjZEdWVNa2xwUzFmSXhOaFI3alh4ZXREeWhuUHVHd1hISnNqZVFsdURLeEN3dERnKwoxbXAyT1pvRTBMOTduUFRZRWFwS0F5eTR6a2ZXRGZQdVBaN1ovM0JxNWpoTWdIYmJydFFUc2VHWHNmL3c4UU51CjBkdERVZ3R2SDVFeUtPVnZscnVMWmZ5Zkx0UllxNCtGaUlVZHcxdXU1U1FyOW5OVFlPck5xbWNDZ1lFQSthSjAKb0dhNG1BNmxoNlZUZVdsSHF1YmFCMXl6OFU1ZHBJRmJEZTV4Y0F4RG9RL3U1Z2NGNlVscnRxaUdLRXNQR3FVMApVQ0x2UCtkTUVHRmdZRkdBQzZpZ2RVMkJLVDNTMlkrbi9hblQxR2R2TitpRndSNGVDVGtKcG9Hd1RPK1FlVkpJCkZvRlhNeEQwQTJKMllDVHlBcURvZzcvT2lGSGJzazFad1JkQTR2OENnWUVBNEtlMmIyZXpXdXBRb0VmSmg4NVYKWjBtQWhrMlU0d0ZKSldaOVZKZEIzZEVXb0pmVFlVOTR1TTN1cnNPeHNWdVRpaEY4a2VmeHpnbGQrYmNIREdaMwozMWdhSjRTcnA1TGV3SFF1RDRzY2JOdlg3WHVrK0M5dWM3NGZRcUNteUcrSUFPTHBFV0tJZHFoZlRYSWNrN3Y3CkZtY3I3NlY4SXduM3d6RGR3a043NCtFQ2dZRUFrRHpnM0VsZUFXWDlHTnBhMS8wUHp0eWlQN3k5c0FEU3RKbVYKYmdCSEJUSGc1YkFhSGtrU2prL0E4QUtCdWNoY3lzMkg0NEc3OFpXSWFyS0pDRDR2R1ExdTRUaE9GL0ZENGpkUwpIb3hBL0NwanBjOHhjWHNnYWIzT0tLb29udHVSQTdpYU5INjVUcVZPQ0tLY3VVSy9udXN3VGVmR3d4ZGhOSzNpCjNXRzlPU3NDZ1lFQXVZdDB3Q3lVMWNlOXh2ZmZSUm9vK3NqMXIzZ2lyUlRiRWNWRVBHUHdWZVBqYmhiMEUrOGwKNnZiODIwSEZwbnZudE9OM3ZobU1MVDNLLzhLczF4YVMzVGNIeDJlWmJSS1UvSzQ3cFBxOFMweFp4SDNid0w4ago1ZWQvbng3WSsyZWdIYndHbUEreTNXZ1dIbzkxaGJ2cXRpQmFaeFgyMUd1TmpWa1JHdTF6d1JnPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=

controlplane ~/.kube ➜  cd /root/

controlplane ~ ➜  

controlplane ~ ➜  ls -la
total 64
drwx------ 1 root root 4096 Sep 10 14:21 .
dr-xr-xr-x 1 root root 4096 Sep 10 14:21 ..
-rw-r--r-- 1 root root 1272 Sep 10 14:07 .bash_profile
-rw-r--r-- 1 root root 3265 Feb 18  2026 .bashrc
drwxr-xr-x 1 root root 4096 Sep 10 14:16 .cache
drwxr-xr-x 2 root root 4096 Sep 10 14:16 CKA
drwxr-xr-x 1 root root 4096 Feb 18  2026 .config
drwxr-xr-x 3 root root 4096 Sep 10 14:08 .kube
-rw-r--r-- 1 root root 1456 Sep 10 14:21 my-kube-config
-rw-r--r-- 1 root root  161 Jul  9  2019 .profile
-rw-r--r-- 1 root root    0 Sep  9 07:56 sample.yaml
drwx------ 2 root root 4096 Sep 10 14:16 .ssh
drwx------ 2 root root 4096 Sep 10 14:17 .terminal_logs
drwxr-xr-x 4 root root 4096 Feb 18  2026 .vim
-rw-r--r-- 1 root root  132 Feb 18  2026 .vimrc
-rw-r--r-- 1 root root  165 Feb 18  2026 .wget-hsts

controlplane ~ ➜  catt my-kube-config 
-bash: catt: command not found

controlplane ~ ✖ cat my-kube-config 
apiVersion: v1
kind: Config

clusters:
- name: production
  cluster:
    certificate-authority: /etc/kubernetes/pki/ca.crt
    server: https://controlplane:6443

- name: development
  cluster:
    certificate-authority: /etc/kubernetes/pki/ca.crt
    server: https://controlplane:6443

- name: kubernetes-on-aws
  cluster:
    certificate-authority: /etc/kubernetes/pki/ca.crt
    server: https://controlplane:6443

- name: test-cluster-1
  cluster:
    certificate-authority: /etc/kubernetes/pki/ca.crt
    server: https://controlplane:6443

contexts:
- name: test-user@development
  context:
    cluster: development
    user: test-user

- name: aws-user@kubernetes-on-aws
  context:
    cluster: kubernetes-on-aws
    user: aws-user

- name: test-user@production
  context:
    cluster: production
    user: test-user

- name: research
  context:
    cluster: test-cluster-1
    user: dev-user

users:
- name: test-user
  user:
    client-certificate: /etc/kubernetes/pki/users/test-user/test-user.crt
    client-key: /etc/kubernetes/pki/users/test-user/test-user.key
- name: dev-user
  user:
    client-certificate: /etc/kubernetes/pki/users/dev-user/developer-user.crt
    client-key: /etc/kubernetes/pki/users/dev-user/dev-user.key
- name: aws-user
  user:
    client-certificate: /etc/kubernetes/pki/users/aws-user/aws-user.crt
    client-key: /etc/kubernetes/pki/users/aws-user/aws-user.key

current-context: test-user@development
preferences: {}


controlplane ~ ➜  kubectl config current-context --kubeconfig my-kube-config 
test-user@development

controlplane ~ ➜  kubectl config use-context --h
error: unknown flag: --h
See 'kubectl config use-context --help' for usage.

controlplane ~ ✖ kubectl config use-context -h
Set the current-context in a kubeconfig file.

Aliases:
use-context, use

Examples:
  # Use the context for the minikube cluster
  kubectl config use-context minikube

Usage:
  kubectl config use-context CONTEXT_NAME [options]

Use "kubectl options" for a list of global command-line options (applies to all commands).

controlplane ~ ➜  kubectl config current-context --kubeconfig my-kube-config 
test-user@development

controlplane ~ ➜  kubectl config --kubeconfig=/root/my-kube-config current-context
test-user@development

controlplane ~ ➜  

controlplane ~ ➜  kubectl config --kubeconfig=/root/my-kube-config use-context research
Switched to context "research".

controlplane ~ ➜  kubectl config --kubeconfig=/root/my-kube-config use-context research
Switched to context "research".

controlplane ~ ➜  kubectl config --kubeconfig=/root/my-kube-config current-context
research

controlplane ~ ➜  

controlplane ~ ➜  vi ~/.bashrc

controlplane ~ ➜  

controlplane ~ ➜  source ~/.bashrc

controlplane ~ ➜  kubectl config --kubeconfig=/root/my-kube-config current-context
research

controlplane ~ ➜  

controlplane ~ ➜  

controlplane ~ ➜  kubectl get pods
error: unable to read client-cert /etc/kubernetes/pki/users/dev-user/developer-user.crt for dev-user due to open /etc/kubernetes/pki/users/dev-user/developer-user.crt: no such file or directory

controlplane ~ ✖ 

controlplane ~ ✖ ls -ltr  /etc/kubernetes/pki/users/
total 12
drwxr-xr-x 2 root root 4096 Sep 10 14:16 test-user
drwxr-xr-x 2 root root 4096 Sep 10 14:16 dev-user
drwxr-xr-x 2 root root 4096 Sep 10 14:16 aws-user

controlplane ~ ➜  cd  /etc/kubernetes/pki/users/

controlplane kubernetes/pki/users ➜  ls -ltr
total 12
drwxr-xr-x 2 root root 4096 Sep 10 14:16 test-user
drwxr-xr-x 2 root root 4096 Sep 10 14:16 dev-user
drwxr-xr-x 2 root root 4096 Sep 10 14:16 aws-user

controlplane kubernetes/pki/users ➜  cd aws-user/

controlplane pki/users/aws-user ➜  ls -ltr
total 12
-rw------- 1 root root 1704 Sep 10 14:21 aws-user.key
-rw-r--r-- 1 root root  924 Sep 10 14:21 aws-user.csr
-rw-r--r-- 1 root root 1025 Sep 10 14:21 aws-user.crt

controlplane pki/users/aws-user ➜  cat aws-user.
cat: aws-user.: No such file or directory

controlplane pki/users/aws-user ✖ cat aws-user.key 
-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCseuhvK+9KXpHG
7O/ADKX22lK0LYhc9xzueeVkReWg6DsjBl7bkOU4Ij/wfc82nrjCoz+sWhGL3fg7
7OEtFrpGvo2lSFoLdeQftYkFUzLdQwZB/SslpLDa2oc0NOi1nRI9pQv3rNz0yw9c
CeDkvZM+T+VUC5mIE9nb5XKfrADQLVA69j979uQsoyxJtTm9omZIoERqtYLuRE9u
ZSFaXWMSdQ8R0H97jiPJ5l/GpDK/ffDpSGSGIDeKhMdZXpR0j4kBN9vNx6PMU4jr
5mDmHl6rq64YKBgAb2zww/6FqVUdxhgojHFbRclwW14effVino42XjKsyNd1tD8A
iWXJ+KdjAgMBAAECggEADo8+Jqrv7fhcrYzw/Lu0mMlmLip3y9faRoaIpssVrrGx
KEGQk/qVDC+BSTo9hHqn1a+fyjCSMZsrqgH9d2e8krM21BXERW+5XDSKm/tMHGGy
L14rxxIyEaSybBBD9+y0jk/r2jI/4Ulw2E/x1C1CjCyEtcWtkKSTATJ1rLqBbmZ5
PtgG4IkH/YNpc3NXvAH32hLmpYUI+1Knkj9DdTV6Wq+JTrTXjlQMjla97ulI2gtv
PpmJPlZhgMVLRVmK/hhx0XlnUJlfmg9PcHtyDvUY/jE3+5FgsMwLNvOnXVuGZMhX
Db4kvp9VbrrwWqitl29b9j89St2qE6sVPVkL+E7jEQKBgQDirXZhXgUgHxmWFoRC
0P3YOs/UIG0GEx4PZQMIlx0NsH6nybJz0Ch++GMPM3e0nz9qC+MPHe9ZGbhfWXTR
pXuvr3nQcwAdf/pcEL8KBCGJNiMLejMNuS6Hqu2M3Gi9qall7MBlMv9v4b+/t6VK
A50fPEaLMhz+vqZA+HnUUFfp0wKBgQDCyqt+nE9LNEIxrJ5DyzUjrIZvXFJp4dpb
TAy5wwPjUrZaCS81iFq8bHsyQ/jabdGFVBXhGeFkPrUosGYCKRHNJxzs2gbD6JV6
o2Hl9hY5vxHuphHHwAz/cvolUpWt69Jq0+Ssio8TbLO9TRPX49T/wB+2QFv6lpfb
Ye+3a2HCMQKBgB3etcbG2O4OqxR4Cx2y5IBl35UYYMV4J3Hn4ap0H0P6ifYaQgW4
3F0+5e7O3WtTwMt8nYMUcsHO/diytQ4bPF0+RlMNlGpOvvL60fHD8ZdfJucQR0H7
sQH3qC3zrWmwvb3MoN21Bqv7l4Tv8jv6le3Tx4f4JpH7FXViSMuNesg5AoGAVa8I
2NyxFIecRnWD+JY+fb66M+oMZn7uqhI91sitwST1CY3YsleUciXV2zqDELIV4+wk
46uatZnP3mIZvQGLzw5Rbu5I44w/lH6h5aHmDOi7Xpq2X4NfNE7DMf+tz59YI52p
jSw123mJZs+s1t5lJ0q/qE+PJh9wFRRzed9GVUECgYBG0ABW3uIncJLAL1rgGZ0G
luuw9NnjWjGv/n96Bwd8SWHPOdg/XEBjnUycNvIUtT04IFOJEdxctcpZs1emCPKF
4NgITN8TE98BlOYYxrP2HNt7MXsXHU1OiFsPyhtoHWPDJE34Gr+L0xdaHtqNWRLV
eqyz7X+2X8E0wPDeMLDtyw==
-----END PRIVATE KEY-----

controlplane pki/users/aws-user ➜  

controlplane pki/users/aws-user ➜  

controlplane pki/users/aws-user ➜  kubectl config view --kubeconfig=/root/my-kube-config | grep -A5 "name: dev-user"
- name: dev-user
  user:
    client-certificate: /etc/kubernetes/pki/users/dev-user/developer-user.crt
    client-key: /etc/kubernetes/pki/users/dev-user/dev-user.key
- name: test-user
  user:

controlplane pki/users/aws-user ➜  ls -ltr /etc/kubernetes/pki/users/dev-user/
total 12
-rw------- 1 root root 1704 Sep 10 14:21 dev-user.key
-rw-r--r-- 1 root root  924 Sep 10 14:21 dev-user.csr
-rw-r--r-- 1 root root 1025 Sep 10 14:21 dev-user.crt

controlplane pki/users/aws-user ➜  kubectl config set-credentials -h
Set a user entry in kubeconfig.

 Specifying a name that already exists will merge new fields on top of existing values.

        Client-certificate flags:
        --client-certificate=certfile --client-key=keyfile
        
        Bearer token flags:
        --token=bearer_token
        
        Basic auth flags:
        --username=basic_user --password=basic_password
        
 Bearer token and basic auth are mutually exclusive.

Examples:
  # Set only the "client-key" field on the "cluster-admin"
  # entry, without touching other values
  kubectl config set-credentials cluster-admin --client-key=~/.kube/admin.key
  
  # Set basic auth for the "cluster-admin" entry
  kubectl config set-credentials cluster-admin --username=admin --password=uXFGweU9l35qcif
  
  # Embed client certificate data in the "cluster-admin" entry
  kubectl config set-credentials cluster-admin --client-certificate=~/.kube/admin.crt --embed-certs=true
  
  # Enable the Google Compute Platform auth provider for the "cluster-admin" entry
  kubectl config set-credentials cluster-admin --auth-provider=gcp
  
  # Enable the OpenID Connect auth provider for the "cluster-admin" entry with additional arguments
  kubectl config set-credentials cluster-admin --auth-provider=oidc --auth-provider-arg=client-id=foo
--auth-provider-arg=client-secret=bar
  
  # Remove the "client-secret" config value for the OpenID Connect auth provider for the "cluster-admin" entry
  kubectl config set-credentials cluster-admin --auth-provider=oidc --auth-provider-arg=client-secret-
  
  # Enable new exec auth plugin for the "cluster-admin" entry
  kubectl config set-credentials cluster-admin --exec-command=/path/to/the/executable
--exec-api-version=client.authentication.k8s.io/v1beta1
  
  # Enable new exec auth plugin for the "cluster-admin" entry with interactive mode
  kubectl config set-credentials cluster-admin --exec-command=/path/to/the/executable
--exec-api-version=client.authentication.k8s.io/v1beta1 --exec-interactive-mode=Never
  
  # Define new exec auth plugin arguments for the "cluster-admin" entry
  kubectl config set-credentials cluster-admin --exec-arg=arg1 --exec-arg=arg2
  
  # Create or update exec auth plugin environment variables for the "cluster-admin" entry
  kubectl config set-credentials cluster-admin --exec-env=key1=val1 --exec-env=key2=val2
  
  # Remove exec auth plugin environment variables for the "cluster-admin" entry
  kubectl config set-credentials cluster-admin --exec-env=var-to-remove-

Options:
    --auth-provider='':
        Auth provider for the user entry in kubeconfig

    --auth-provider-arg=[]:
        'key=value' arguments for the auth provider

    --client-certificate='':
        Path to client-certificate file for the user entry in kubeconfig

    --client-key='':
        Path to client-key file for the user entry in kubeconfig

    --embed-certs=false:
        Embed client cert/key for the user entry in kubeconfig

    --exec-api-version='':
        API version of the exec credential plugin for the user entry in kubeconfig

    --exec-arg=[]:
        New arguments for the exec credential plugin command for the user entry in kubeconfig

    --exec-command='':
        Command for the exec credential plugin for the user entry in kubeconfig

    --exec-env=[]:
        'key=value' environment values for the exec credential plugin

    --exec-interactive-mode='':
        InteractiveMode of the exec credentials plugin for the user entry in kubeconfig

    --exec-provide-cluster-info=false:
        ProvideClusterInfo of the exec credentials plugin for the user entry in kubeconfig

    --password='':
        password for the user entry in kubeconfig

    --token='':
        token for the user entry in kubeconfig

    --username='':
        username for the user entry in kubeconfig

Usage:
  kubectl config set-credentials NAME [--client-certificate=path/to/certfile] [--client-key=path/to/keyfile]
[--token=bearer_token] [--username=basic_user] [--password=basic_password] [--auth-provider=provider_name]
[--auth-provider-arg=key=value] [--exec-command=exec_command] [--exec-api-version=exec_api_version] [--exec-arg=arg]
[--exec-env=key=value] [options]

Use "kubectl options" for a list of global command-line options (applies to all commands).

controlplane pki/users/aws-user ✖ 

controlplane pki/users/aws-user ✖ kubectl config view --kubeconfig=/root/my-kube-config | grep -A5 "name: dev-user"
- name: dev-user
  user:
    client-certificate: /etc/kubernetes/pki/users/dev-user/developer-user.crt
    client-key: /etc/kubernetes/pki/users/dev-user/dev-user.key
- name: test-user
  user:

controlplane pki/users/aws-user ➜  

controlplane pki/users/aws-user ➜  

controlplane pki/users/aws-user ➜  ls -l /etc/kubernetes/pki/users/dev-user/
total 12
-rw-r--r-- 1 root root 1025 Sep 10 14:21 dev-user.crt
-rw-r--r-- 1 root root  924 Sep 10 14:21 dev-user.csr
-rw------- 1 root root 1704 Sep 10 14:21 dev-user.key

controlplane pki/users/aws-user ➜  

controlplane pki/users/aws-user ➜  kubectl config set-credentials dev-user \
  --client-certificate=/etc/kubernetes/pki/users/dev-user/dev-user.crt \
  --client-key=/etc/kubernetes/pki/users/dev-user/dev-user.key \
  --kubeconfig=/root/my-kube-config
User "dev-user" set.

controlplane pki/users/aws-user ➜  kubectl get pods
No resources found in default namespace.

controlplane pki/users/aws-user ➜  kubectl config view --kubeconfig=/root/my-kube-config | grep -A5 "name: dev-user"
- name: dev-user
  user:
    client-certificate: /etc/kubernetes/pki/users/dev-user/dev-user.crt
    client-key: /etc/kubernetes/pki/users/dev-user/dev-user.key
- name: test-user
  user:

controlplane pki/users/aws-user ➜  
