Service Accounts
##########################


controlplane ~ ➜  k get sa
NAME      AGE
default   8m16s
dev       23s

controlplane ~ ➜  k get deployments.apps 
NAME            READY   UP-TO-DATE   AVAILABLE   AGE
web-dashboard   1/1     1            1           15s

controlplane ~ ➜  k describe deployments.apps web-dashboard
Name:                   web-dashboard
Namespace:              default
CreationTimestamp:      Sun, 13 Sep 2026 13:44:17 +0000
Labels:                 <none>
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               name=web-dashboard
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:  name=web-dashboard
  Containers:
   web-dashboard:
    Image:      gcr.io/kodekloud/customimage/my-kubernetes-dashboard
    Port:       8080/TCP
    Host Port:  0/TCP
    Environment:
      PYTHONUNBUFFERED:  1
    Mounts:              <none>
  Volumes:               <none>
  Node-Selectors:        <none>
  Tolerations:           <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   web-dashboard-6b774f6458 (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  33s   deployment-controller  Scaled up replica set web-dashboard-6b774f6458 from 0 to 1

controlplane ~ ➜  k describe pod web-dashboard
Name:             web-dashboard-6b774f6458-4d74f
Namespace:        default
Priority:         0
Service Account:  default
Node:             controlplane/10.244.166.114
Start Time:       Sun, 13 Sep 2026 13:44:17 +0000
Labels:           name=web-dashboard
                  pod-template-hash=6b774f6458
Annotations:      <none>
Status:           Running
IP:               10.22.0.9
IPs:
  IP:           10.22.0.9
Controlled By:  ReplicaSet/web-dashboard-6b774f6458
Containers:
  web-dashboard:
    Container ID:   containerd://cef1d4143e926239a86cf7262a257a9176ac71f64ade4a79925d3f2982b2036d
    Image:          gcr.io/kodekloud/customimage/my-kubernetes-dashboard
    Image ID:       gcr.io/kodekloud/customimage/my-kubernetes-dashboard@sha256:7d70abe342b13ff1c4242dc83271ad73e4eedb04e2be0dd30ae7ac8852193069
    Port:           8080/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Sun, 13 Sep 2026 13:44:27 +0000
    Ready:          True
    Restart Count:  0
    Environment:
      PYTHONUNBUFFERED:  1
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-wjmh6 (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   True 
  Initialized                 True 
  Ready                       True 
  ContainersReady             True 
  PodScheduled                True 
Volumes:
  kube-api-access-wjmh6:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    Optional:                false
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  104s  default-scheduler  Successfully assigned default/web-dashboard-6b774f6458-4d74f to controlplane
  Normal  Pulling    104s  kubelet            spec.containers{web-dashboard}: Pulling image "gcr.io/kodekloud/customimage/my-kubernetes-dashboard"
  Normal  Pulled     96s   kubelet            spec.containers{web-dashboard}: Successfully pulled image "gcr.io/kodekloud/customimage/my-kubernetes-dashboard" in 8.374s (8.374s including waiting). Image size: 31659887 bytes.
  Normal  Created    96s   kubelet            spec.containers{web-dashboard}: Container created
  Normal  Started    95s   kubelet            spec.containers{web-dashboard}: Container started


controlplane ~ ➜  k get pods -o yaml 
apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2026-09-13T13:44:17Z"
    generateName: web-dashboard-6b774f6458-
    generation: 1
    labels:
      name: web-dashboard
      pod-template-hash: 6b774f6458
    name: web-dashboard-6b774f6458-4d74f
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: web-dashboard-6b774f6458
      uid: ac874ee2-e399-4170-8396-7d4be6ec17b9
    resourceVersion: "897"
    uid: e3cbb37c-9a2f-4e3f-950c-e772a3052ad3
  spec:
    containers:
    - env:
      - name: PYTHONUNBUFFERED
        value: "1"
      image: gcr.io/kodekloud/customimage/my-kubernetes-dashboard
      imagePullPolicy: Always
      name: web-dashboard
      ports:
      - containerPort: 8080
        protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-wjmh6
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: controlplane
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-wjmh6
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2026-09-13T13:44:27Z"
      observedGeneration: 1
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2026-09-13T13:44:17Z"
      observedGeneration: 1
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2026-09-13T13:44:27Z"
      observedGeneration: 1
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2026-09-13T13:44:27Z"
      observedGeneration: 1
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2026-09-13T13:44:17Z"
      observedGeneration: 1
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://cef1d4143e926239a86cf7262a257a9176ac71f64ade4a79925d3f2982b2036d
      image: gcr.io/kodekloud/customimage/my-kubernetes-dashboard:latest
      imageID: gcr.io/kodekloud/customimage/my-kubernetes-dashboard@sha256:7d70abe342b13ff1c4242dc83271ad73e4eedb04e2be0dd30ae7ac8852193069
      lastState: {}
      name: web-dashboard
      ready: true
      resources: {}
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2026-09-13T13:44:27Z"
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-wjmh6
        readOnly: true
        recursiveReadOnly: Disabled
    hostIP: 10.244.166.114
    hostIPs:
    - ip: 10.244.166.114
    observedGeneration: 1
    phase: Running
    podIP: 10.22.0.9
    podIPs:
    - ip: 10.22.0.9
    qosClass: BestEffort
    startTime: "2026-09-13T13:44:17Z"
kind: List
metadata:
  resourceVersion: ""

controlplane ~ ➜  k create serviceaccount -h
Create a service account with the specified name.

Aliases:
serviceaccount, sa

Examples:
  # Create a new service account named my-service-account
  kubectl create serviceaccount my-service-account

Options:
    --allow-missing-template-keys=true:
        If true, ignore any errors in templates when a field or map key is missing in the template. Only applies to
        golang and jsonpath output formats.

    --dry-run='none':
        Must be "none", "server", or "client". If client strategy, only print the object that would be sent, without
        sending it. If server strategy, submit server-side request without persisting the resource.

    --field-manager='kubectl-create':
        Name of the manager used to track field ownership.

    -o, --output='':
        Output format. One of: (json, yaml, kyaml, name, go-template, go-template-file, template, templatefile,
        jsonpath, jsonpath-as-json, jsonpath-file).

    --save-config=false:
        If true, the configuration of current object will be saved in its annotation. Otherwise, the annotation will
        be unchanged. This flag is useful when you want to perform kubectl apply on this object in the future.

    --show-managed-fields=false:
        If true, keep the managedFields when printing objects in JSON or YAML format.

    --template='':
        Template string or path to template file to use when -o=go-template, -o=go-template-file. The template format
        is golang templates [http://golang.org/pkg/text/template/#pkg-overview].

    --validate='strict':
        Must be one of: strict (or true), warn, ignore (or false). "true" or "strict" will use a schema to validate
        the input and fail the request if invalid. It will perform server side validation if ServerSideFieldValidation
        is enabled on the api-server, but will fall back to less reliable client-side validation if not. "warn" will
        warn about unknown or duplicate fields without blocking the request if server-side field validation is enabled
        on the API server, and behave as "ignore" otherwise. "false" or "ignore" will not perform any schema
        validation, silently dropping any unknown or duplicate fields.

Usage:
  kubectl create serviceaccount NAME [--dry-run=server|client|none] [options]

Use "kubectl options" for a list of global command-line options (applies to all commands).

controlplane ~ ➜  k create serviceaccount dashboard-sa
serviceaccount/dashboard-sa created

controlplane ~ ➜  

controlplane ~ ➜  cd /var/rbac/

controlplane /var/rbac ➜  ls -ltr
total 8
-rw-r--r--    1 root     root           191 Aug  4 07:57 pod-reader-role.yaml
-rw-r--r--    1 root     root           399 Aug  4 07:57 dashboard-sa-role-binding.yaml

controlplane /var/rbac ➜  cat dashboard-sa-role-binding.yaml 
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
  namespace: default
subjects:
- kind: ServiceAccount
  name: dashboard-sa # Name is case sensitive
  namespace: default
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: pod-reader # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

controlplane /var/rbac ➜  

controlplane /var/rbac ➜  k create token dashboard-sa 
eyJhbGciOiJSUzI1NiIsImtpZCI6IlY5Q01PVWtwYXBFSlVOWG11QWY1c2NYdG9uUHFid3hEUWVtQ2NZU3RqMmMifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiLCJrM3MiXSwiZXhwIjoxNzg5MzEwOTc5LCJpYXQiOjE3ODkzMDczNzksImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiODllMTRkZmUtMTM1OC00NzhhLTlhMzAtZGI1MmFmZDkxMTQ2Iiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZWZhdWx0Iiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImRhc2hib2FyZC1zYSIsInVpZCI6IjQ2OWNiOGVhLWIzZGEtNDU4Yi04OWNjLWRjOTE4MmJhZDEwZCJ9fSwibmJmIjoxNzg5MzA3Mzc5LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVmYXVsdDpkYXNoYm9hcmQtc2EifQ.BJpu2B-iWRBcqlyQbPYPaXeDZaySYFZ9AcSny04Jv4wzmgMIg6itx_LIQms9Ryq-X6odV54v-9BWh3PM-wSYZ7byLCSuL-uCb8w0FHSDVZcLU2zhSKBCoIh4PwXWXsW5lwCXk84vk-iTOx9RzMmrICT99g3KUklJDFTAGd72ZXs1z-BfnQiHYmys06lI8jeFnCZtdQfuje3Tu1Gfh_x2lFhLHf7WU0gvM3bG5Dsi2Go26-yHV9SyF72p5mV74CDIfqm4g_5R1sOGBO3zEjecm0hZ_x7b2atyDI7eaHUcFXvZci8UC6pv5TWsB7s6ezDPhVbi-_q7wOmJoNLNOXxYoA

controlplane /var/rbac ➜  k get serviceaccounts 
NAME           AGE
dashboard-sa   2m43s
default        15m
dev            7m9s

controlplane /var/rbac ➜  

controlplane /var/rbac ➜  k describe serviceaccounts dashboard-sa 
Name:                dashboard-sa
Namespace:           default
Labels:              <none>
Annotations:         <none>
Image pull secrets:  <none>
Events:              <none>

controlplane /var/rbac ➜  

controlplane /var/rbac ➜  k get deployments.apps 
NAME            READY   UP-TO-DATE   AVAILABLE   AGE
web-dashboard   1/1     1            1           7m13s

controlplane /var/rbac ➜  k edit deployments.apps web-dashboard 
error: deployments.apps "web-dashboard" is invalid
A copy of your changes has been stored to "/tmp/kubectl-edit-3563644087.yaml"
error: Edit cancelled, no valid changes were saved.

controlplane /var/rbac ✖ 

controlplane /var/rbac ✖ k apply -f /tmp/kubectl-edit-3563644087.yaml
Warning: resource deployments/web-dashboard is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
The request is invalid: patch: Invalid value: "map[metadata:map[annotations:map[kubectl.kubernetes.io/last-applied-configuration:{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"annotations\":{\"deployment.kubernetes.io/revision\":\"1\"},\"creationTimestamp\":\"2026-09-13T13:44:17Z\",\"generation\":1,\"name\":\"web-dashboard\",\"namespace\":\"default\",\"resourceVersion\":\"901\",\"uid\":\"c17891ab-76c8-4a0b-82d9-4bc5c4b88a9c\"},\"spec\":{\"progressDeadlineSeconds\":600,\"replicas\":1,\"revisionHistoryLimit\":10,\"selector\":{\"matchLabels\":{\"name\":\"web-dashboard\"}},\"strategy\":{\"rollingUpdate\":{\"maxSurge\":\"25%\",\"maxUnavailable\":\"25%\"},\"type\":\"RollingUpdate\"},\"template\":{\"metadata\":{\"labels\":{\"name\":\"web-dashboard\"}},\"spec\":{\"containers\":[{\"env\":[{\"name\":\"PYTHONUNBUFFERED\",\"value\":\"1\"}],\"image\":\"gcr.io/kodekloud/customimage/my-kubernetes-dashboard\",\"imagePullPolicy\":\"Always\",\"name\":\"web-dashboard\",\"ports\":[{\"containerPort\":8080,\"protocol\":\"TCP\"}],\"resources\":{},\"terminationMessagePath\":\"/dev/termination-log\",\"terminationMessagePolicy\":\"File\"}],\"dnsPolicy\":\"ClusterFirst\",\"restartPolicy\":\"Always\",\"schedulerName\":\"default-scheduler\",\"securityContext\":{},\"seriveAccountName\":\"dashboard-sa\",\"terminationGracePeriodSeconds\":30}}},\"status\":{\"availableReplicas\":1,\"conditions\":[{\"lastTransitionTime\":\"2026-09-13T13:44:27Z\",\"lastUpdateTime\":\"2026-09-13T13:44:27Z\",\"message\":\"Deployment has minimum availability.\",\"reason\":\"MinimumReplicasAvailable\",\"status\":\"True\",\"type\":\"Available\"},{\"lastTransitionTime\":\"2026-09-13T13:44:17Z\",\"lastUpdateTime\":\"2026-09-13T13:44:27Z\",\"message\":\"ReplicaSet \\\"web-dashboard-6b774f6458\\\" has successfully progressed.\",\"reason\":\"NewReplicaSetAvailable\",\"status\":\"True\",\"type\":\"Progressing\"}],\"observedGeneration\":1,\"readyReplicas\":1,\"replicas\":1,\"terminatingReplicas\":0,\"updatedReplicas\":1}}\n]] spec:map[template:map[spec:map[seriveAccountName:dashboard-sa]]]]": strict decoding error: unknown field "spec.template.spec.seriveAccountName"

controlplane /var/rbac ✖ kubectl set serviceaccount deploy/web-dashboard dashboard-sa
deployment.apps/web-dashboard serviceaccount updated

controlplane /var/rbac ➜  

controlplane /var/rbac ➜  k edit deployments.apps web-dashboard 
Edit cancelled, no changes made.

controlplane /var/rbac ➜  

controlplane /var/rbac ➜  k get serviceaccounts 
NAME           AGE
dashboard-sa   8m54s
default        21m
dev            13m

controlplane /var/rbac ➜  k edit serviceaccounts dashboard-sa
error: serviceaccounts "dashboard-sa" is invalid
serviceaccount/dashboard-sa edited

controlplane /var/rbac ➜  

controlplane /var/rbac ➜  k describe serviceaccounts dashboard-sa
Name:                dashboard-sa
Namespace:           default
Labels:              <none>
Annotations:         <none>
Image pull secrets:  <none>
Events:              <none>

controlplane /var/rbac ➜  

controlplane /var/rbac ➜  k edit deployments.apps web-dashboard 
Edit cancelled, no changes made.

controlplane /var/rbac ➜  vi webapp.yaml

controlplane /var/rbac ➜  

controlplane /var/rbac ➜  k apply -f webapp.yaml 
Warning: resource deployments/web-dashboard is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
deployment.apps/web-dashboard configured

controlplane /var/rbac ➜  k get pods
NAME                             READY   STATUS        RESTARTS   AGE
web-dashboard-5c474c779d-v8hmv   1/1     Running       0          10s
web-dashboard-7dd5d9cc74-c9q78   1/1     Terminating   0          5m27s

controlplane /var/rbac ➜  k get pods
NAME                             READY   STATUS        RESTARTS   AGE
web-dashboard-5c474c779d-v8hmv   1/1     Running       0          19s
web-dashboard-7dd5d9cc74-c9q78   1/1     Terminating   0          5m36s

controlplane /var/rbac ➜  kubectl exec $(kubectl get pod -l name=web-dashboard -o jsonpath='{.items[0].metadata.name}') -- ls /var/run/secrets/kubernetes.io/serviceaccount/
token

controlplane /var/rbac ➜  

controlplane /var/rbac ➜  
